Add Deep Lake as an optional vector store
yoheinakajima/babyagi pull request #311
Opened 2023-05-11 19:33 UTC by mcleonard

This adds an extension for using Deep Lake as the vector store.

2023-05-15 18:47 UTC, adolkhan requested changes

2023-05-15 18:47 UTC, adolkhan commented on extensions/deeplake.py
> +        self.dataset = deeplake.empty(dataset, token=token)
`deeplake.empty` is used either to create a new dataset or overwrite an existing dataset. To overwrite you will need to use `overwrite=True`.


But what if dataset already exists? it is better to add a check:

```suggestion
        if overwrite=True or not deeplake.exists(dataset, token=token, **creds):
             self.dataset = deeplake.empty(dataset, token=token, overwrite=True, **creds)
             
             self.dataset.create_tensor(
                 "task",
                 htype="text",
                 create_id_tensor=False,
                 create_sample_info_tensor=False,
                 create_shape_tensor=False,
                 chunk_compression="lz4",
             )

             self.dataset.create_tensor(
                 "result",
                 htype="text",
                 create_id_tensor=False,
                 create_sample_info_tensor=False,
                 create_shape_tensor=False,
                 chunk_compression="lz4",
             )

             self.dataset.create_tensor(
                 "embedding",
                 htype="generic",
                 dtype=np.float64,
                 create_id_tensor=False,
                 create_sample_info_tensor=False,
                 max_chunk_size=64 * MB,
                 create_shape_tensor=True,
             )
        else:
            self.dataset = deeplake.load(dataset, token=token, **creds)
```

2023-05-15 18:47 UTC, adolkhan commented on extensions/deeplake.py
> +            "task",
Also don't we have any kind of metadata associated with the dataset, like the date when the file was created and so on? If BabyAgi doesn't support it, it's fine we can skip it, but if we do want to add metadata, then we can create a separate tensor:

```
        self.dataset.create_tensor(
             "metadata",
             htype="json",
             create_id_tensor=False,
             create_sample_info_tensor=False,
             create_shape_tensor=False,
             chunk_compression="lz4",
         )
```

2023-05-15 18:47 UTC, adolkhan commented on extensions/requirements.txt
> +deeplake==3.4.1
We will be adding bench of new features, better not to fix the version
```suggestion
deeplake>=3.4.1
```

2023-05-15 18:56 UTC, adolkhan commented
Broader comments, we need to add tests and a very simple use case on how to use babyAGI with DeepLake (also maybe part of the tests). It can even be a random data, just to make sure that it works as intended.

2023-05-23 22:57 UTC, mikayelh commented
@yoheinakajima, i wonder if this can be reviewed on your end as well - BabyAgi would benefit from another OSS vector store! (we're also working on a use case that's based on this integration).

2024-09-30 08:37 UTC, closed without merging